version: "3.8"

services:
  db:
    container_name: postgres  
    image: mariadb:11.2.3
    hostname: ${DB_HOST}
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - connection

  app:
    container_name: gocrud
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_DEV: ${APP_DEV}
      APP_WEB: ${APP_WEB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - connection

networks:
  connection:
    driver: bridge